module.exports = {
  rules: {
    semi: ['error', 'never'],
    quotes: ['error', 'single'],
    indent: ['error', 2],
    'space-before-function-paren': ['error', 'always'],
    'no-trailing-spaces': 'error',
    'no-var': 'error',
    'prefer-const': 'error',
    'no-const-assign': 'error',
    'no-new-object': 'error',
    'no-new-func': 'error',
    'no-array-constructor': 'error',
    'object-shorthand': 'error',
    'quote-props': ['error', 'as-needed'],
    'prefer-object-spread': 'error',
    'array-callback-return': ['error'],
    'prefer-template': ['error'],
    'template-curly-spacing': ['error'],
    'no-eval': ['error'],
    'no-useless-escape': ['error'],
    'wrap-iife': ['error'],
    'prefer-rest-params': ['error'],
    'default-param-last': ['error'],
    'prefer-spread': ['error'],
    'prefer-arrow-callback': ['error'],
    'arrow-spacing': ['error'],
    'arrow-parens': ['error', 'as-needed', { requireForBlockBody: true }],
    'no-useless-constructor': ['error'],
  }
}
