module.exports = {
  env: {
    es6: true,
    browser: true,
    node: true,
  },
  ignorePatterns: [
    '*.d.ts',
    'dist',
    'LICENSE*',
    'package-lock.json',
    'pnpm-lock.yaml',
    'yarn.lock',
  ],
  plugins: [
    'import',
    'lzy',
  ],
  rules: {
    semi: ['error', 'always'],
    quotes: ['error', 'single'],
    indent: ['error', 2, { SwitchCase: 1 }],
    'keyword-spacing': ['error', { before: true, after: true }],
    'comma-spacing': ['error', { before: false, after: true }],
    'arrow-spacing': ['error', { before: true, after: true }],
    'array-bracket-spacing': ['error', 'never'],
    'object-curly-spacing': ['error', 'always'],
    'space-before-function-paren': ['error', 'always'],
    'no-trailing-spaces': 'error',
    'no-var': 'error',
    'prefer-const': 'error',
    'no-undef': 'off',
    'no-const-assign': 'error',
    'no-new-object': 'error',
    'no-new-func': 'error',
    'no-array-constructor': 'error',
    'object-shorthand': 'error',
    'quote-props': ['error', 'as-needed'],
    'prefer-object-spread': 'error',
    'array-callback-return': 'error',
    'prefer-template': 'error',
    'template-curly-spacing': 'error',
    'no-eval': 'error',
    'no-useless-escape': 'error',
    'wrap-iife': 'error',
    'prefer-rest-params': 'error',
    'default-param-last': 'error',
    'prefer-spread': 'error',
    'prefer-arrow-callback': 'error',
    'arrow-parens': ['error', 'as-needed', { requireForBlockBody: true }],
    'no-useless-constructor': 'error',
    'import/no-mutable-exports': 'error',
    'import/first': 'error',
    'object-curly-newline': 'error',
    'dot-notation': ['error', { allowKeywords: true }],
    'one-var': ['error', { initialized: 'never' }],
    'comma-dangle': ['error', 'always-multiline'],
    'operator-linebreak': ['error', 'after', { overrides: { '?': 'before', ':': 'before', '|>': 'before' } }],
    'no-unused-vars': 'error',
    'no-case-declarations': 'error',
    'no-unneeded-ternary': ['error', { defaultAssignment: true }],
    'no-mixed-operators': ['error', {
      groups: [
        ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
        ['&&', '||'],
        ['in', 'instanceof'],
      ],
      allowSamePrecedence: true,
    }],
    'brace-style': ['error', '1tbs', { allowSingleLine: true }],
    'capitalized-comments': 'off',
    'multiline-comment-style': 'off',
    'no-inline-comments': 'off',
    'spaced-comment': ['error', 'always', { line: { exceptions: ['-', '+', '='] }, block: { exceptions: ['*'] } }],
    'line-comment-position': 'off',
    'lines-around-comment': 'off',
    'no-spaced-func': 'error',
    'no-redeclare': 'error',
    'no-dupe-keys': 'error',
    'no-dupe-args': 'error',
    'no-duplicate-case': 'error',
    'no-func-assign': 'error',

    // lzy plugin
    'lzy/object-shorthand-top': 'error',
    'lzy/zh-en-space': ['error', { lintComments: true, lintTemplate: true, lintString: false }],
  },
}
